export const AUTH_ERROR_CODES = {
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PHONE_ALREADY_EXISTS: "PHONE_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
} as const;

export const SYSTEM_ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  DATABASE_CONNECTION_LOST: "DATABASE_CONNECTION_LOST",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
} as const;

export type TAuthErrorCode = keyof typeof AUTH_ERROR_CODES;
export type TSystemErrorCode = keyof typeof SYSTEM_ERROR_CODES;
