import type { ProductSpecSheet } from "@nhatnang/core";

export const INDUSTRIAL_DIESEL_GENERATOR_TEMPLATE: ProductSpecSheet = [
  {
    groupKey: "general",
    titleVi: "Thông số chung",
    titleEn: "General Specifications",
    order: 1,
    items: [
      {
        key: "continuous_power",
        nameVi: "Công suất liên tục",
        nameEn: "Prime Power",
        value: "",
        unit: "kVA",
      },
      {
        key: "standby_power",
        nameVi: "Công suất dự phòng",
        nameEn: "Standby Power",
        value: "",
        unit: "kVA",
      },
      {
        key: "voltage",
        nameVi: "Điện thế",
        nameEn: "Voltage",
        value: "230/400",
        unit: "V",
      },
      {
        key: "frequency",
        nameVi: "Tần số",
        nameEn: "Frequency",
        value: "50",
        unit: "Hz",
      },
      {
        key: "current",
        nameVi: "Dòng điện định mức",
        nameEn: "Rated Current",
        value: "",
        unit: "A",
      },
      {
        key: "fuel_tank",
        nameVi: "Dung tích bình nhiên liệu",
        nameEn: "Fuel Tank Capacity",
        value: "",
        unit: "L",
      },
      {
        key: "fuel_consumption",
        nameVi: "Tiêu hao nhiên liệu (100% tải)",
        nameEn: "Fuel Consumption (100% load)",
        value: "",
        unit: "L/h",
      },
      {
        key: "noise_level",
        nameVi: "Độ ồn cách 7m",
        nameEn: "Noise Level @ 7m",
        value: "68",
        unit: "dB(A)",
      },
      {
        key: "dimensions",
        nameVi: "Kích thước (Dài x Rộng x Cao)",
        nameEn: "Dimensions (L x W x H)",
        value: "",
        unit: "mm",
      },
      {
        key: "weight",
        nameVi: "Trọng lượng",
        nameEn: "Weight",
        value: "",
        unit: "kg",
      },
    ],
  },
  {
    groupKey: "engine",
    titleVi: "Động cơ",
    titleEn: "Engine",
    order: 2,
    items: [
      {
        key: "engine_brand",
        nameVi: "Hãng sản xuất động cơ",
        nameEn: "Engine Manufacturer",
        value: "",
        unit: "",
      },
      {
        key: "engine_model",
        nameVi: "Model động cơ",
        nameEn: "Engine Model",
        value: "",
        unit: "",
      },
      {
        key: "engine_power",
        nameVi: "Công suất động cơ",
        nameEn: "Engine Output Power",
        value: "",
        unit: "kW",
      },
      {
        key: "rated_speed",
        nameVi: "Tốc độ vòng quay",
        nameEn: "Rated Speed",
        value: "1500",
        unit: "vòng/phút",
      },
      {
        key: "cylinders",
        nameVi: "Số xi lanh & Bố trí",
        nameEn: "Cylinders & Layout",
        value: "",
        unit: "",
      },
      {
        key: "displacement",
        nameVi: "Dung tích xi lanh",
        nameEn: "Displacement",
        value: "",
        unit: "cc",
      },
      {
        key: "cooling_system",
        nameVi: "Hệ thống làm mát",
        nameEn: "Cooling System",
        value: "Két nước tuần hoàn",
        unit: "",
      },
      {
        key: "governor_type",
        nameVi: "Điều tốc",
        nameEn: "Governor Type",
        value: "Điện tử",
        unit: "",
      },
      {
        key: "lube_capacity",
        nameVi: "Dung tích dầu bôi trơn",
        nameEn: "Lube Oil Capacity",
        value: "",
        unit: "L",
      },
      {
        key: "coolant_capacity",
        nameVi: "Dung tích nước làm mát",
        nameEn: "Coolant Capacity",
        value: "",
        unit: "L",
      },
    ],
  },
  {
    groupKey: "alternator",
    titleVi: "Đầu phát điện",
    titleEn: "Alternator",
    order: 3,
    items: [
      {
        key: "alternator_brand",
        nameVi: "Hãng sản xuất đầu phát",
        nameEn: "Alternator Manufacturer",
        value: "",
        unit: "",
      },
      {
        key: "alternator_model",
        nameVi: "Model đầu phát",
        nameEn: "Alternator Model",
        value: "",
        unit: "",
      },
      {
        key: "alternator_type",
        nameVi: "Kiểu đầu phát",
        nameEn: "Alternator Type",
        value: "Không chổi than (Brushless)",
        unit: "",
      },
      {
        key: "power_factor",
        nameVi: "Hệ số công suất",
        nameEn: "Power Factor",
        value: "0.8",
        unit: "cosφ",
      },
      {
        key: "voltage_regulator",
        nameVi: "Bộ điều chỉnh điện áp",
        nameEn: "Voltage Regulator",
        value: "AVR",
        unit: "",
      },
      {
        key: "insulation_class",
        nameVi: "Cấp cách điện",
        nameEn: "Insulation Class",
        value: "H",
        unit: "",
      },
      {
        key: "protection_class",
        nameVi: "Cấp bảo vệ",
        nameEn: "Protection Degree",
        value: "IP23",
        unit: "",
      },
    ],
  },
  {
    groupKey: "controller",
    titleVi: "Bảng điều khiển & Bảo vệ",
    titleEn: "Controller & Protection",
    order: 4,
    items: [
      {
        key: "controller_model",
        nameVi: "Model bảng điều khiển",
        nameEn: "Controller Model",
        value: "ComAp AMF20",
        unit: "",
      },
      {
        key: "display_type",
        nameVi: "Màn hình hiển thị",
        nameEn: "Display Type",
        value: "LCD đa thông số",
        unit: "",
      },
      {
        key: "ats_port",
        nameVi: "Cổng kết nối ATS",
        nameEn: "ATS Connection Port",
        value: "Có",
        unit: "",
      },
      {
        key: "protection_functions",
        nameVi: "Chức năng bảo vệ",
        nameEn: "Protection Functions",
        value:
          "Bảo vệ áp suất nhớt thấp, quá nhiệt nước, quá tải, tần số cao/thấp",
        unit: "",
      },
    ],
  },
];

export const GASOLINE_PORTABLE_GENERATOR_TEMPLATE: ProductSpecSheet = [
  {
    groupKey: "general",
    titleVi: "Thông số chung",
    titleEn: "General Specifications",
    order: 1,
    items: [
      {
        key: "continuous_power",
        nameVi: "Công suất liên tục",
        nameEn: "Rated Output",
        value: "",
        unit: "kW",
      },
      {
        key: "max_power",
        nameVi: "Công suất tối đa",
        nameEn: "Maximum Output",
        value: "",
        unit: "kW",
      },
      {
        key: "voltage",
        nameVi: "Điện áp ra",
        nameEn: "Output Voltage",
        value: "230",
        unit: "V",
      },
      {
        key: "frequency",
        nameVi: "Tần số",
        nameEn: "Frequency",
        value: "50",
        unit: "Hz",
      },
      {
        key: "phase",
        nameVi: "Số pha",
        nameEn: "Phase",
        value: "1 pha",
        unit: "",
      },
      {
        key: "start_method",
        nameVi: "Kiểu khởi động",
        nameEn: "Starting Method",
        value: "Đề điện / Giật nổ",
        unit: "",
      },
      {
        key: "fuel_tank",
        nameVi: "Dung tích bình xăng",
        nameEn: "Fuel Tank",
        value: "",
        unit: "L",
      },
      {
        key: "run_time_50",
        nameVi: "Thời gian chạy 50% tải",
        nameEn: "Run Time @ 50% Load",
        value: "",
        unit: "giờ",
      },
      {
        key: "noise_level",
        nameVi: "Độ ồn cách 7m",
        nameEn: "Noise Level @ 7m",
        value: "70",
        unit: "dB(A)",
      },
      {
        key: "weight",
        nameVi: "Trọng lượng",
        nameEn: "Weight",
        value: "",
        unit: "kg",
      },
      {
        key: "dimensions",
        nameVi: "Kích thước (D x R x C)",
        nameEn: "Dimensions",
        value: "",
        unit: "mm",
      },
    ],
  },
  {
    groupKey: "engine",
    titleVi: "Động cơ xăng",
    titleEn: "Gasoline Engine",
    order: 2,
    items: [
      {
        key: "engine_model",
        nameVi: "Model động cơ",
        nameEn: "Engine Model",
        value: "",
        unit: "",
      },
      {
        key: "displacement",
        nameVi: "Dung tích xi lanh",
        nameEn: "Displacement",
        value: "",
        unit: "cc",
      },
      {
        key: "engine_type",
        nameVi: "Kiểu động cơ",
        nameEn: "Engine Type",
        value: "4 thì, 1 xi lanh, làm mát bằng gió",
        unit: "",
      },
      {
        key: "oil_capacity",
        nameVi: "Dung tích nhớt",
        nameEn: "Oil Capacity",
        value: "1.1",
        unit: "L",
      },
      {
        key: "fuel_type",
        nameVi: "Nhiên liệu",
        nameEn: "Fuel",
        value: "Xăng không chì",
        unit: "",
      },
    ],
  },
  {
    groupKey: "features",
    titleVi: "Tính năng & Cổng ra",
    titleEn: "Features & Outlets",
    order: 3,
    items: [
      {
        key: "voltage_regulation",
        nameVi: "Điều chỉnh điện áp",
        nameEn: "Voltage Regulation",
        value: "AVR / Inverter Pure Sine Wave",
        unit: "",
      },
      {
        key: "ac_sockets",
        nameVi: "Ổ cắm AC đầu ra",
        nameEn: "AC Outlets",
        value: "2 x 230V/16A",
        unit: "",
      },
      {
        key: "dc_outlets",
        nameVi: "Cổng DC đầu ra",
        nameEn: "DC Output",
        value: "12V - 8.3A",
        unit: "",
      },
      {
        key: "low_oil_alert",
        nameVi: "Cảnh báo nhớt thấp",
        nameEn: "Low Oil Shutdown",
        value: "Có (Tự động tắt máy)",
        unit: "",
      },
      {
        key: "overload_protection",
        nameVi: "Bảo vệ quá tải",
        nameEn: "Overload Protection",
        value: "Có",
        unit: "",
      },
    ],
  },
];

export const DIESEL_STANDBY_GENERATOR_TEMPLATE: ProductSpecSheet = [
  {
    groupKey: "general",
    titleVi: "Thông số chung",
    titleEn: "General Specifications",
    order: 1,
    items: [
      {
        key: "continuous_power",
        nameVi: "Công suất liên tục",
        nameEn: "Continuous Power",
        value: "",
        unit: "kW",
      },
      {
        key: "max_power",
        nameVi: "Công suất dự phòng",
        nameEn: "Max Standby Power",
        value: "",
        unit: "kW",
      },
      {
        key: "voltage",
        nameVi: "Điện thế ra",
        nameEn: "Output Voltage",
        value: "230V (hoặc 400V)",
        unit: "V",
      },
      {
        key: "frequency",
        nameVi: "Tần số",
        nameEn: "Frequency",
        value: "50",
        unit: "Hz",
      },
      {
        key: "current",
        nameVi: "Dòng điện định mức",
        nameEn: "Rated Current",
        value: "",
        unit: "A",
      },
      {
        key: "fuel_tank",
        nameVi: "Bình nhiên liệu",
        nameEn: "Fuel Tank Capacity",
        value: "15",
        unit: "L",
      },
      {
        key: "fuel_consumption",
        nameVi: "Mức tiêu hao nhiên liệu",
        nameEn: "Fuel Consumption",
        value: "1.7",
        unit: "L/h",
      },
      {
        key: "noise_level",
        nameVi: "Độ ồn cách 7m (có vỏ)",
        nameEn: "Noise Level @ 7m",
        value: "72",
        unit: "dB(A)",
      },
      {
        key: "weight",
        nameVi: "Trọng lượng toàn bộ",
        nameEn: "Gross Weight",
        value: "",
        unit: "kg",
      },
      {
        key: "dimensions",
        nameVi: "Kích thước D x R x C",
        nameEn: "Dimensions",
        value: "",
        unit: "mm",
      },
    ],
  },
  {
    groupKey: "engine",
    titleVi: "Động cơ dầu",
    titleEn: "Diesel Engine",
    order: 2,
    items: [
      {
        key: "engine_model",
        nameVi: "Model động cơ",
        nameEn: "Engine Model",
        value: "D450",
        unit: "",
      },
      {
        key: "engine_power",
        nameVi: "Công suất động cơ",
        nameEn: "Engine Output",
        value: "11",
        unit: "HP",
      },
      {
        key: "displacement",
        nameVi: "Dung tích xi lanh",
        nameEn: "Displacement",
        value: "456",
        unit: "cc",
      },
      {
        key: "start_method",
        nameVi: "Kiểu khởi động",
        nameEn: "Starting System",
        value: "Đề điện 12V",
        unit: "",
      },
      {
        key: "cooling_system",
        nameVi: "Làm mát",
        nameEn: "Cooling",
        value: "Gió cưỡng bức",
        unit: "",
      },
      {
        key: "oil_capacity",
        nameVi: "Dung tích dầu bôi trơn",
        nameEn: "Lube Oil Capacity",
        value: "1.65",
        unit: "L",
      },
    ],
  },
  {
    groupKey: "controller",
    titleVi: "Bảng điều khiển & Tủ ATS",
    titleEn: "Controller & ATS",
    order: 3,
    items: [
      {
        key: "voltage_regulator",
        nameVi: "Bộ điều chỉnh điện áp",
        nameEn: "Voltage Regulation",
        value: "AVR tự động",
        unit: "",
      },
      {
        key: "ats_compatible",
        nameVi: "Kết nối tủ ATS",
        nameEn: "ATS Compatible",
        value: "Có sẵn cổng kết nối",
        unit: "",
      },
      {
        key: "display",
        nameVi: "Hệ thống hiển thị",
        nameEn: "Display",
        value: "Đồng hồ kỹ thuật số LED hiển thị V, A, Hz, giờ chạy",
        unit: "",
      },
      {
        key: "protection",
        nameVi: "Hệ thống bảo vệ",
        nameEn: "Protection",
        value: "Bảo vệ áp suất dầu thấp, quá tải, dòng rò",
        unit: "",
      },
    ],
  },
];

export const UPS_ONLINE_TEMPLATE: ProductSpecSheet = [
  {
    groupKey: "general",
    titleVi: "Thông số chung",
    titleEn: "General Specifications",
    order: 1,
    items: [
      {
        key: "capacity_kva",
        nameVi: "Công suất kVA",
        nameEn: "Capacity (kVA)",
        value: "",
        unit: "kVA",
      },
      {
        key: "capacity_kw",
        nameVi: "Công suất kW",
        nameEn: "Capacity (kW)",
        value: "",
        unit: "kW",
      },
      {
        key: "topology",
        nameVi: "Công nghệ",
        nameEn: "Topology",
        value: "Online Double Conversion (Chuyển đổi kép trực tuyến)",
        unit: "",
      },
      {
        key: "transfer_time",
        nameVi: "Thời gian chuyển mạch",
        nameEn: "Transfer Time",
        value: "0",
        unit: "ms",
      },
      {
        key: "form_factor",
        nameVi: "Kiểu dáng",
        nameEn: "Form Factor",
        value: 'Tower (hoặc Rackmount 19")',
        unit: "",
      },
      {
        key: "dimensions",
        nameVi: "Kích thước D x R x C",
        nameEn: "Dimensions",
        value: "",
        unit: "mm",
      },
      {
        key: "weight",
        nameVi: "Trọng lượng",
        nameEn: "Weight",
        value: "",
        unit: "kg",
      },
    ],
  },
  {
    groupKey: "input",
    titleVi: "Thông số nguồn vào (Input)",
    titleEn: "Input Specifications",
    order: 2,
    items: [
      {
        key: "input_voltage_range",
        nameVi: "Dải điện áp đầu vào",
        nameEn: "Input Voltage Range",
        value: "110 - 300",
        unit: "VAC",
      },
      {
        key: "input_frequency_range",
        nameVi: "Dải tần số đầu vào",
        nameEn: "Input Frequency Range",
        value: "46 - 54",
        unit: "Hz",
      },
      {
        key: "input_power_factor",
        nameVi: "Hệ số công suất đầu vào",
        nameEn: "Input Power Factor",
        value: "> 0.99",
        unit: "",
      },
      {
        key: "input_phase",
        nameVi: "Số pha đầu vào",
        nameEn: "Input Phase",
        value: "1 pha (2 dây + tiếp địa)",
        unit: "",
      },
    ],
  },
  {
    groupKey: "output",
    titleVi: "Thông số nguồn ra (Output)",
    titleEn: "Output Specifications",
    order: 3,
    items: [
      {
        key: "output_voltage",
        nameVi: "Điện áp ra",
        nameEn: "Output Voltage",
        value: "220 ± 1%",
        unit: "VAC",
      },
      {
        key: "output_frequency",
        nameVi: "Tần số ra",
        nameEn: "Output Frequency",
        value: "50/60 ± 0.1%",
        unit: "Hz",
      },
      {
        key: "output_waveform",
        nameVi: "Dạng sóng ngõ ra",
        nameEn: "Output Waveform",
        value: "Sin chuẩn (Pure Sine Wave)",
        unit: "",
      },
      {
        key: "output_power_factor",
        nameVi: "Hệ số công suất ngõ ra",
        nameEn: "Output Power Factor",
        value: "0.9",
        unit: "",
      },
      {
        key: "crest_factor",
        nameVi: "Tỷ số đỉnh dòng điện",
        nameEn: "Crest Factor",
        value: "3:1",
        unit: "",
      },
      {
        key: "overload_capability",
        nameVi: "Khả năng quá tải",
        nameEn: "Overload Capacity",
        value: "105% - 125% trong 1 phút, 125% - 150% trong 30 giây",
        unit: "",
      },
      {
        key: "outlets",
        nameVi: "Ổ cắm ngõ ra",
        nameEn: "Output Sockets",
        value: "IEC C13/C19 & Terminal Block",
        unit: "",
      },
    ],
  },
  {
    groupKey: "battery",
    titleVi: "Ắc quy & Thời gian lưu",
    titleEn: "Battery & Runtime",
    order: 4,
    items: [
      {
        key: "battery_type",
        nameVi: "Loại Ắc quy",
        nameEn: "Battery Type",
        value: "Ắc quy trong (hoặc Tủ ắc quy ngoài)",
        unit: "",
      },
      {
        key: "dc_voltage",
        nameVi: "Điện áp hệ Ắc quy",
        nameEn: "DC Bus Voltage",
        value: "",
        unit: "VDC",
      },
      {
        key: "recharge_time",
        nameVi: "Thời gian nạp lại (90%)",
        nameEn: "Recharge Time to 90%",
        value: "4 - 6",
        unit: "giờ",
      },
      {
        key: "backup_time",
        nameVi: "Thời gian lưu điện tiêu chuẩn",
        nameEn: "Typical Backup Time",
        value: "",
        unit: "phút",
      },
    ],
  },
  {
    groupKey: "communication",
    titleVi: "Giao tiếp & Môi trường",
    titleEn: "Communication & Environment",
    order: 5,
    items: [
      {
        key: "ports",
        nameVi: "Cổng giao tiếp",
        nameEn: "Interface Ports",
        value: "RS232, USB, khe cắm card SNMP",
        unit: "",
      },
      {
        key: "display",
        nameVi: "Màn hình hiển thị",
        nameEn: "Display",
        value: "Màn hình LCD đa chức năng & LED",
        unit: "",
      },
      {
        key: "noise_level",
        nameVi: "Độ ồn",
        nameEn: "Noise Level",
        value: "< 55",
        unit: "dB(A) @ 1m",
      },
      {
        key: "operating_temp",
        nameVi: "Nhiệt độ hoạt động",
        nameEn: "Operating Temperature",
        value: "0 - 40",
        unit: "°C",
      },
    ],
  },
];
