import Link from "next/link";
import { ArrowRight, Database, BookOpen, Layers, Zap } from "lucide-react";

export default function HomePage() {
  const lastUpdated = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="flex min-h-screen flex-col">
      {/* Hero Section */}
      <div className="flex flex-1 items-center justify-center bg-linear-to-br from-zinc-900 via-zinc-950 to-black text-white">
        <div className="mx-auto max-w-3xl px-6 py-16 text-center">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-zinc-700 bg-zinc-900 px-4 py-1.5 text-sm">
            <Zap className="h-4 w-4 text-emerald-400" />
            Hyundai Ecommerce Documentation
          </div>

          <h1 className="mb-4 text-6xl font-bold tracking-tighter">
            Technical Documentation
          </h1>
          <p className="mx-auto mb-8 max-w-xl text-2xl text-zinc-400">
            Hyundai Industrial Equipment E-commerce System
          </p>

          <div className="flex items-center justify-center gap-4">
            <Link
              href="/docs"
              className="flex items-center gap-2 rounded-2xl bg-white px-8 py-4 text-lg font-semibold text-black transition-all hover:bg-zinc-200"
            >
              Explore Documentation
              <ArrowRight className="h-5 w-5" />
            </Link>

            <Link
              href="/docs/database-schema"
              className="flex items-center gap-2 rounded-2xl border border-zinc-700 px-8 py-4 font-medium transition-all hover:border-zinc-400"
            >
              <Database className="h-5 w-5" />
              View Database Schema
            </Link>
          </div>

          {/* Dynamic Last Updated */}
          <p className="mt-10 text-sm text-zinc-500">
            Auto-generated by Drizzle + Fumadocs • Last updated:{" "}
            <span className="font-medium text-zinc-400">{lastUpdated}</span>
          </p>
        </div>
      </div>

      {/* Quick Access */}
      <div className="border-t border-zinc-800 bg-zinc-950 py-16">
        <div className="mx-auto max-w-5xl px-6">
          <h2 className="mb-10 text-center text-2xl font-semibold text-white">
            Quick Access
          </h2>

          <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">
            {/* Card 1 */}
            <Link
              href="/docs/database-schema"
              className="group rounded-3xl border border-zinc-800 bg-zinc-900 p-8 transition-all hover:border-emerald-500 hover:bg-zinc-800"
            >
              <Database className="mb-6 h-10 w-10 text-emerald-400" />
              <h3 className="mb-2 text-xl font-semibold">Database Schema</h3>
              <p className="text-sm text-zinc-400">
                ERD, tables, relationships and migrations
              </p>
            </Link>

            {/* Card 2 */}
            <Link
              href="/docs/architecture"
              className="group rounded-3xl border border-zinc-800 bg-zinc-900 p-8 transition-all hover:border-blue-500 hover:bg-zinc-800"
            >
              <Layers className="mb-6 h-10 w-10 text-blue-400" />
              <h3 className="mb-2 text-xl font-semibold">
                System Architecture
              </h3>
              <p className="text-sm text-zinc-400">
                Monorepo, Turborepo, domain-driven design
              </p>
            </Link>

            {/* Card 3 */}
            <Link
              href="/docs/api"
              className="group rounded-3xl border border-zinc-800 bg-zinc-900 p-8 transition-all hover:border-violet-500 hover:bg-zinc-800"
            >
              <BookOpen className="mb-6 h-10 w-10 text-violet-400" />
              <h3 className="mb-2 text-xl font-semibold">API Reference</h3>
              <p className="text-sm text-zinc-400">
                Next.js App Router API routes
              </p>
            </Link>

            {/* Card 4 */}
            <div className="group rounded-3xl border border-zinc-800 bg-zinc-900 p-8 transition-all hover:border-amber-500 hover:bg-zinc-800">
              <Zap className="mb-6 h-10 w-10 text-amber-400" />
              <h3 className="mb-2 text-xl font-semibold">Getting Started</h3>
              <p className="text-sm text-zinc-400">
                Development environment setup guide
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Footer note */}
      <div className="border-t border-zinc-800 py-8 text-center text-sm text-zinc-500">
        Hyundai Ecommerce Documentation • Built with Fumadocs + Drizzle ORM
      </div>
    </div>
  );
}
