export const ERROR_MESSAGES = {
  TOO_MANY_REQUESTS: "Too Many Requests",
} as const;

export const PG_ERROR_CODE = {
  UNIQUE_VIOLATION: "23505",
  FOREIGN_KEY_VIOLATION: "23503",
  NOT_NULL_VIOLATION: "23502",
  EXCLUSION_VIOLATION: "23P01",
  DEADLOCK_DETECTED: "40P01",
  INVALID_TEXT_REPRESENTATION: "22P02",
  QUERY_CANCELED: "57014",
  UNDEFINED_COLUMN: "42703",
  UNDEFINED_TABLE: "42P01",
} as const;
