export const CATALOG_ROUTES = {
  PRODUCTS: {
    TAG: "products",
    PREFIX: "products",
    FIND_ALL: "",
    METADATA: "metadata",
    FIND_BY_ID: ":id",
    CREATE: "",
    UPDATE: ":id",
    DELETE: ":id",
  },
  CATEGORIES: {
    TAG: "categories",
    PREFIX: "categories",
    FIND_ALL: "",
    TREE: "tree",
    FIND_BY_ID: ":id",
    CREATE: "",
    UPDATE: ":id",
    DELETE: ":id",
  },
  BRANDS: {
    TAG: "brands",
    PREFIX: "brands",
    FIND_ALL: "",
    FIND_BY_ID: ":id",
    CREATE: "",
    UPDATE: ":id",
    DELETE: ":id",
  },
} as const;
