// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HomePage": {
    "brand": "HYUNDAI",
    "branchName": "Nhật Năng",
    "nav": {
      "products": "Sản phẩm",
      "solutions": "Giải pháp",
      "services": "Dịch vụ"
    },
    "header": {
      "support": "Hỗ trợ 24/7",
      "requestQuote": "Yêu cầu báo giá"
    },
    "hero": {
      "badge": "Dòng tải nặng",
      "titleLine1": "Nguồn điện",
      "titleLine2": "không gián đoạn.",
      "description": "Đảm bảo hoạt động liên tục cho doanh nghiệp với máy phát điện công nghiệp Hyundai. Được thiết kế để đạt độ tin cậy tuyệt đối trong điều kiện khắc nghiệt.",
      "primaryCta": "Khám phá máy phát điện",
      "secondaryCta": "Tư vấn",
      "imageAlt": "Hệ thống máy phát điện công nghiệp Hyundai"
    },
    "categories": {
      "title": "HẠNG MỤC CHÍNH",
      "subtitle": "Chuyên môn kỹ thuật"
    },
    "promos": {
      "badge": "Khuyến mại mùa",
      "title": "MÙA HÈ 2026",
      "subtitle": "CHƯƠNG TRÌNH KHUYẾN MẠI PRECISION",
      "desc": "Nâng cấp cơ sở hạ tầng của bạn với tiết kiệm 20% cho tất cả các đơn vị công nghiệp. Thời gian hạn chế.",
      "discount": "-20%",
      "cta": "Tìm hiểu thêm"
    },
    "products": {
      "title": "Dòng Hyundai",
      "subtitle": "Đơn vị bán chạy nhất",
      "buy_now_cta": "Mua ngay"
    },
    "news": {
      "title": "HIỂU BIẾT KỸ THUẬT",
      "subtitle": "Kiến thức chuyên gia",
      "viewAll": "Xem tất cả bài viết",
      "article1": {
        "category": "Bảo trì",
        "title": "Cách tối đa hóa tuổi thọ máy phát của bạn thêm 40%",
        "desc": "Các hệ thống lọc và làm mát dầu thích hợp là xương sống của độ bền điện lực công nghiệp...",
        "date": "12 tháng 11, 2026 • 5 phút đọc"
      },
      "article2": {
        "category": "Cải tiến",
        "title": "Chuyển hướng sang hybrid: Tích hợp năng lượng mặt trời với sao lưu diesel",
        "desc": "Giảm dấu chân carbon trong khi duy trì 100% thời gian hoạt động không còn là giấc mơ...",
        "date": "28 tháng 10, 2026 • 8 phút đọc"
      }
    },
    "trust": {
      "warranty": {
        "title": "Bảo hành được chứng nhận",
        "desc": "Bảo hành nhà sản xuất chính thức 2 năm cho tất cả các đơn vị điện Hyundai công nghiệp và dân dụng."
      },
      "support": {
        "title": "Hỗ trợ kỹ thuật 24/7",
        "desc": "Các kỹ sư chuyên gia của chúng tôi luôn sẵn sàng hỗ trợ khẩn cấp cơ sở hạ tầng quan trọng."
      },
      "dealer": {
        "title": "Nhà phân phối được uỷ quyền",
        "desc": "Kết nối trực tiếp với Hyundai Power Vietnam, đảm bảo phụ tùng chính hãng và giá hợp lý."
      }
    },
    "footer": {
      "description": "Đồng hành cùng doanh nghiệp bằng giải pháp năng lượng ổn định, kỹ thuật vượt trội và hỗ trợ kỹ thuật 24/7.",
      "newsletterLabel": "Cập nhật kỹ thuật",
      "emailPlaceholder": "Nhập email doanh nghiệp",
      "subscribe": "Đăng ký",
      "productsTitle": "Sản phẩm",
      "supportTitle": "Hỗ trợ",
      "contactQuote": "Liên hệ & Báo giá",
      "warrantyPolicy": "Chính sách bảo hành",
      "technicalDocs": "Tài liệu kỹ thuật",
      "allRightsReserved": "Bảo lưu mọi quyền.",
      "privacyPolicy": "Chính sách quyền riêng tư.",
      "termsOfService": "Điều khoản dịch vụ.",
      "products": {
        "industrialGenerators": "Máy phát công nghiệp",
        "residentialGen": "Máy phát dân dụng",
        "portablePower": "Nguồn điện di động",
        "atsPanels": "Tủ ATS"
      }
    }
  }
};
export default messages;