name: CI
on:
  push:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "docs/**"

jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-latest

    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Lint Code
        run: bun run lint
