name: Storefront App CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      storefront: ${{ steps.filter.outputs.storefront }}
    steps:
      - uses: actions/checkout@v7
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.2
        id: filter
        with:
          filters: |
            storefront:
              - "storefront/**"
              - ".github/workflows/storefront.yml"

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.storefront == 'true' }}
    name: Release to Vercel
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Environment
        uses: ./.github/setup-environment

      - name: Final Safety Check (Lint, Test)
        working-directory: storefront
        run: |
          bun install
          bun run check-types
          bun run lint
          bun test
      - name: Deploy to Vercel
        uses: ./.github/vercel-deploy
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
